project_id = "ohvtqsjyvfctjapqpbtf"

[functions]

[functions.delete-account]
verify_jwt = false

[functions.check-link-safety]
verify_jwt = false

[functions.admin-list-users]
verify_jwt = false

[functions.moderate-image]
verify_jwt = false

[functions.send-contact-email]
verify_jwt = false

[functions.download-attachment]
verify_jwt = false

