project_id = "ohvtqsjyvfctjapqpbtf"

[functions]

[functions.delete-account]
verify_jwt = false

[functions.check-link-safety]
verify_jwt = false

[functions.admin-list-users]
verify_jwt = false

[functions.phone-otp-send]
verify_jwt = false

[functions.phone-otp-verify]
verify_jwt = false
