
-- 1. Add bio column to profiles
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS bio TEXT;

-- 2. Remove previous seed posts so we can replace with the new teen-themed batch
DELETE FROM public.answers WHERE post_id IN (SELECT id FROM public.posts WHERE is_seed = true);
DELETE FROM public.reports WHERE post_id IN (SELECT id FROM public.posts WHERE is_seed = true);
DELETE FROM public.bookmarks WHERE post_id IN (SELECT id FROM public.posts WHERE is_seed = true);
DELETE FROM public.posts WHERE is_seed = true;

-- 3. Insert 60 fresh seed posts (Indian boy authors, ages 10-19, relatable topics + media)
INSERT INTO public.posts (title, description, category, is_seed, seed_author_name, image_url, video_url, likes, views, created_at) VALUES
-- Cricket / sports
('Bro the way Bumrah bowled yesterday 🔥', 'Did anyone else watch the match last night?? Bumrah''s yorker in the 19th over was UNREAL. I literally jumped off the sofa and my mom got mad coz it was 11pm 😭. How does he even land it on the same spot every single ball? My friend says Starc is better but nahh Bumrah > everyone for me. Who do you guys think is the best death over bowler rn?', 'General', true, 'Aarav Sharma', 'https://images.unsplash.com/photo-1531415074968-036ba1b575da?w=800', NULL, 142, 890, now() - interval '2 hours'),
('Trying to learn Virat''s cover drive 😅', 'So I''ve been practising the cover drive for like 3 weeks now in our gully. Looks great in the mirror but in the actual match I edged it straight to point 🥲. Any tips on weight transfer? I keep going on the back foot and missing the line.', 'General', true, 'Rohan Verma', 'https://images.unsplash.com/photo-1540747913346-19e32dc3e97e?w=800', NULL, 87, 412, now() - interval '5 hours'),
('IPL auction predictions for next year', 'Ok hear me out — I think CSK is gonna pick up a young left arm pacer this time. RCB needs a finisher BADLY. MI will probably retain Suryakumar at any cost. Drop your wildest predictions below 👇', 'General', true, 'Kabir Singh', 'https://images.unsplash.com/photo-1593341646782-e0b495cff86d?w=800', NULL, 203, 1240, now() - interval '8 hours'),

-- Gaming
('BGMI conqueror grind is killing me 😭', 'I''m stuck in Ace 5 stars from past 4 days bro. Every match I get either bots or absolute sweats. Yesterday I had a 12 kill chicken dinner and got only +98 rating. The system is RIGGED I tell you. Anyone else grinding this season?', 'Technology', true, 'Aryan Kapoor', 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=800', NULL, 318, 2100, now() - interval '3 hours'),
('Free Fire vs BGMI debate ends today', 'Look I''ve played both. FF is fun for quick matches but BGMI hits different when you''re in a squad with proper comms. The recoil control, the map design, the gunplay — there''s no comparison really. But FF community is wayyy bigger in my school 🤷', 'Technology', true, 'Vivaan Mehta', 'https://images.unsplash.com/photo-1493711662062-fa541adb3fc8?w=800', NULL, 256, 1580, now() - interval '6 hours'),
('Got my first Ace in Valorant!!! 🎉', 'BROOOOO finally hit an ace today on Haven with Jett. Operator one tap headshots back to back. My team was screaming on mic 😂. Been playing for like 8 months and this is the highlight of my life ngl. Clip in next post.', 'Technology', true, 'Reyansh Gupta', 'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=800', NULL, 401, 2890, now() - interval '12 hours'),
('Should I buy a gaming PC or PS5?', 'Saved up around 80k from gifts over 2 years. Dad says I can use it on a console/PC if I keep my marks above 85%. PC has more games but PS5 has GTA 6 coming. What would you guys do?? I mainly play FPS games and racing.', 'Technology', true, 'Arnav Joshi', 'https://images.unsplash.com/photo-1606144042614-b2417e99c4e3?w=800', NULL, 178, 945, now() - interval '1 day'),
('Minecraft hardcore mode tips needed', 'Day 47 of my hardcore world. Got diamonds, full iron armor, found a village. Now scared to go to nether 😭. Last time I died to a ghast. Any tips for first time nether runs in hardcore? Should I take obsidian to make a backup portal?', 'Technology', true, 'Ishaan Reddy', 'https://images.unsplash.com/photo-1587573089734-09cb69c0f2b4?w=800', NULL, 92, 530, now() - interval '14 hours'),

-- Studies / school
('JEE 2026 prep — am I cooked?', 'Class 11 just started and bro the syllabus is INSANE. I''m good at maths but physics rotational motion is making me question my existence. How are you guys managing school + coaching + self study? I literally have no time for anything else.', 'Education', true, 'Yash Agarwal', 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=800', NULL, 234, 1670, now() - interval '4 hours'),
('Best YouTube channel for class 10 maths?', 'Boards in 6 months and trigonometry is killing me. Tried Khan Academy, Vedantu, Physics Wallah. PW Foundation seems decent but too many ads. What do you guys use?', 'Education', true, 'Dhruv Patel', 'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=800', NULL, 156, 890, now() - interval '7 hours'),
('How to actually study for 8 hours a day??', 'Toppers say they study 8-10 hrs daily. I can barely focus for 2 hours before my brain melts. I''ve tried Pomodoro, study with me videos, even keeping phone in another room. Nothing works for long. Is it a discipline issue or am I just dumb?', 'Education', true, 'Krish Malhotra', 'https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0?w=800', NULL, 489, 3210, now() - interval '10 hours'),
('NCERT vs reference books for boards', 'Teacher says NCERT is enough for boards. Coaching sir says do RD Sharma + RS Aggarwal + HC Verma. Mom is buying everything. My table looks like a library. Be honest — what actually worked for you guys?', 'Education', true, 'Atharv Iyer', 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=800', NULL, 267, 1450, now() - interval '15 hours'),
('Sharing my class 12 physics notes 📚', 'I made detailed handwritten notes for the entire class 12 physics syllabus during my prep. Covering: Electrostatics, Current Electricity, Magnetism, EMI, AC, EM Waves, Optics, Modern Physics, Semiconductors. If anyone needs them DM me, I''ll send the PDF for free. Helped me get 94 in boards 🙏', 'Education', true, 'Shaurya Khanna', 'https://images.unsplash.com/photo-1456735190827-d1262f71b8a3?w=800', NULL, 612, 4180, now() - interval '1 day'),
('Memorizing Periodic Table — easy way?', 'Chemistry test on Friday and I still can''t remember the d-block elements. Tried songs, mnemonics, flash cards. The stupid lanthanides won''t stick in my head. HELP', 'Education', true, 'Aditya Nair', 'https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?w=800', NULL, 89, 467, now() - interval '18 hours'),
('How do you guys remember history dates??', 'SST is my worst subject. So many wars, treaties, dates. Battle of Plassey 1757, Battle of Buxar 1764... bro it all blends together. Any technique that actually works?', 'Education', true, 'Pranav Bhat', 'https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?w=800', NULL, 178, 980, now() - interval '20 hours'),

-- Gym / fitness
('Started gym at 16 — month 2 update 💪', 'When I started I couldn''t even bench the empty bar (20kg). Today I did 35kg for 8 reps. Feels like a small win but I''m hyped. Eating 4 meals a day, drinking lots of milk. My arms are slowly looking less like noodles 😂', 'Lifestyle', true, 'Veer Choudhary', 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800', NULL, 345, 2100, now() - interval '6 hours'),
('Is creatine safe for teenagers?', 'I''m 17, been working out for 6 months. Trainer says I can take creatine. Mom is FREAKING out coz she read some article saying it damages kidneys. What''s the actual truth? Anyone here taking it?', 'Lifestyle', true, 'Harsh Saxena', 'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=800', NULL, 267, 1890, now() - interval '11 hours'),
('Calisthenics vs gym for beginners', 'Don''t have money for gym membership. Watching Chris Heria videos and trying to do pull ups at the park. Currently can do 4 clean ones. Will I get jacked just from bodyweight or do I need weights eventually?', 'Lifestyle', true, 'Madhav Rao', 'https://images.unsplash.com/photo-1599058917212-d750089bc07e?w=800', NULL, 198, 1230, now() - interval '13 hours'),
('Tried protein powder for first time 🥤', 'Bought a 1kg whey from Decathlon. Chocolate flavor. Honestly tastes like sad chocolate milk. But I feel less sore the next day. Worth it or just placebo?', 'Lifestyle', true, 'Devansh Rana', 'https://images.unsplash.com/photo-1593095948071-474c5cc2989d?w=800', NULL, 134, 720, now() - interval '16 hours'),

-- Music / movies
('Anirudh''s new album is FIRE 🔥🔥', 'Just finished listening end to end. Every song slaps. The Tamil-EDM fusion he does is unmatched. Which song is your favourite? I''m obsessed with track 4.', 'Lifestyle', true, 'Tanish Iyer', 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=800', NULL, 289, 1870, now() - interval '5 hours'),
('Underrated Bollywood movies you''ve seen?', 'Bored of all the masala movies. Recently watched Andhadhun and Tumbbad — mind blown. Drop your underrated picks. Looking for thrillers/dark stuff mainly.', 'Lifestyle', true, 'Rudra Sinha', 'https://images.unsplash.com/photo-1489599735734-79b4af4a7d2e?w=800', NULL, 423, 2890, now() - interval '9 hours'),
('Learning guitar — month 4 progress', 'Can finally play Tum Hi Ho without messing up the chords 🥹. Fingers don''t hurt anymore. Next goal: Channa Mereya. Anyone else self-learning? Share your songs!', 'Lifestyle', true, 'Aniket Pillai', 'https://images.unsplash.com/photo-1510915361894-db8b60106cb1?w=800', 'https://videos.pexels.com/video-files/4090954/4090954-uhd_2560_1440_25fps.mp4', 167, 1020, now() - interval '12 hours'),
('Honest review: Spider-Verse Across the Spider-Verse', 'Finally watched it on Netflix. The animation is INSANE. Like every frame is a painting. The story hit hard ngl, the ending made me feel things. Beyond the Spider-Verse better drop soon or I''ll riot.', 'Lifestyle', true, 'Kartik Dubey', 'https://images.unsplash.com/photo-1635805737707-575885ab0820?w=800', NULL, 356, 2300, now() - interval '17 hours'),

-- Tech / gadgets
('Got a OnePlus Nord for my 16th birthday!! 🎉', 'Finally upgraded from my dad''s old Redmi. The cameras are insanee, gaming is buttery smooth, screen looks gorgeous. AMA about it. Also recommend some good cases for it pls.', 'Technology', true, 'Mihir Bansal', 'https://images.unsplash.com/photo-1601784551446-20c9e07cdbdb?w=800', NULL, 234, 1450, now() - interval '8 hours'),
('Best earbuds under 3000?', 'Lost my earbuds in school last week 😭. Need new ones. Looking at Boat Airdopes 161, Realme Buds, Noise Buds. What''s actually good for the price?', 'Technology', true, 'Sahil Kohli', 'https://images.unsplash.com/photo-1606220945770-b5b6c2c55bf1?w=800', NULL, 145, 870, now() - interval '14 hours'),
('Learning Python in class 11 IP', 'Started with print("Hello World") last week. Now doing if-else and loops. It''s actually fun?? I thought coding would be super hard but it''s like solving puzzles. Anyone here who started Python in school and stuck with it?', 'Technology', true, 'Naman Tiwari', 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=800', NULL, 312, 1980, now() - interval '19 hours'),
('How do hackers actually learn hacking?', 'Watched Mr Robot and now I''m obsessed lol. Don''t want to do anything illegal but I find cybersecurity fascinating. Where do I even start? Is TryHackMe worth it as a beginner?', 'Technology', true, 'Vihaan Saxena', 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=800', NULL, 478, 3120, now() - interval '22 hours'),

-- Anime / manga
('One Piece is genuinely peak fiction', 'I started watching One Piece last summer (1000+ episodes are intimidating bro). Now I''m at the Wano arc and I get why people are obsessed. Oda is a genius. Don''t @ me with naruto/aot fans.', 'Lifestyle', true, 'Parth Joshi', 'https://images.unsplash.com/photo-1578632767115-351597cf2477?w=800', NULL, 567, 3890, now() - interval '4 hours'),
('Best anime to start with as a beginner?', 'My friends keep telling me to watch anime. I''ve only seen Death Note. What should I watch next? Heard about Demon Slayer, JJK, Hunter x Hunter. Don''t want anything 500 episodes long pls.', 'Lifestyle', true, 'Siddhant Sen', 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=800', NULL, 345, 2100, now() - interval '11 hours'),
('Reading manga vs watching anime', 'Just finished JJK manga and it''s SO much better than the anime. The pacing, the details, the panels — chef''s kiss. But anime has voice acting and animation. What do you guys prefer?', 'Lifestyle', true, 'Ayush Kumar', 'https://images.unsplash.com/photo-1542856391-010fb87dcfed?w=800', NULL, 234, 1340, now() - interval '16 hours'),

-- Food
('Maggi 2 min hack that changed my life', 'Add an egg, some cheese, leftover veggies, and a dash of soy sauce. Trust me. This is what I survive on after school. My mom calls it disgusting but it''s elite tier midnight food.', 'Lifestyle', true, 'Rishi Bhatia', 'https://images.unsplash.com/photo-1612929633738-8fe44f7ec841?w=800', NULL, 567, 3450, now() - interval '7 hours'),
('Best street food in your city?', 'I''m from Delhi and chole bhature from Sitaram Diwan Chand is unmatched. Pani puri from any random thela > fancy restaurant. What''s your city''s must-try?', 'Lifestyle', true, 'Aaryan Joshi', 'https://images.unsplash.com/photo-1606491956689-2ea866880c84?w=800', NULL, 423, 2670, now() - interval '13 hours'),

-- Life / random
('Class 10 last day — feeling weird 🥲', 'Today was officially the last day of school for class 10. Won''t see most of my classmates again because they''re shifting to different schools/streams. Cried a little ngl. School was annoying but I''m gonna miss it.', 'General', true, 'Ansh Wadhwa', 'https://images.unsplash.com/photo-1523580494863-6f3031224c94?w=800', NULL, 678, 4230, now() - interval '6 hours'),
('How to talk to girls without being weird??', 'Genuine question. Every time I try to talk to my crush I either say something stupid or just freeze. My friends say "just be yourself" — bro myself IS the problem 💀', 'General', true, 'Karan Mishra', 'https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=800', NULL, 892, 6120, now() - interval '9 hours'),
('Parents don''t understand mental health', 'Tried telling mom I''ve been feeling really down lately. Her response: "you''re a kid, what stress do you have, just study". Idk how to even start that conversation. Anyone else dealing with this?', 'General', true, 'Tanmay Pandey', 'https://images.unsplash.com/photo-1499209974431-9dddcece7f88?w=800', NULL, 1234, 8920, now() - interval '15 hours'),
('Saving money as a student is hard af', 'Pocket money: 1500/month. By week 2 it''s already gone on canteen, snacks, recharge. How do you guys save? I want to buy a skateboard but at this rate I''ll be 30 by then.', 'Lifestyle', true, 'Ojas Verma', 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800', NULL, 234, 1450, now() - interval '21 hours'),
('First time travelling alone (train) tomorrow', 'Going from Mumbai to Pune by train alone for the first time. Mom packed enough food for an army. Slightly nervous but also excited?? Any tips for solo train travel?', 'General', true, 'Hriday Khanna', 'https://images.unsplash.com/photo-1474487548417-781cb71495f3?w=800', NULL, 178, 980, now() - interval '23 hours'),

-- Cricket / football
('Real Madrid signing Mbappe was the best thing', 'The Bellingham + Mbappe + Vinicius trio is going to be insane. Liverpool fan turning into a closet RM fan ngl. UCL this year is theirs.', 'General', true, 'Reyaan Bhatt', 'https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=800', NULL, 289, 1780, now() - interval '5 hours'),
('Played football after 6 months today', 'My ankle hurts, my lungs are dying, my legs are jelly. Body said NO at minute 15. Need to start running again I''m so unfit it''s embarrassing.', 'Lifestyle', true, 'Veer Saxena', 'https://images.unsplash.com/photo-1431324155629-1a6deb1dec8d?w=800', 'https://videos.pexels.com/video-files/4761711/4761711-uhd_2560_1440_25fps.mp4', 156, 890, now() - interval '10 hours'),

-- Coding / projects
('Made my first website!! 🥳', 'It''s a basic HTML/CSS portfolio site. Hosted it on Netlify for free. Took me like 2 weeks of YouTube tutorials. Looks ugly but it WORKS and that''s what matters. Next step: learn JavaScript.', 'Technology', true, 'Kunal Saini', 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800', NULL, 412, 2670, now() - interval '12 hours'),
('Should I learn web dev or app dev first?', 'I''m 15 and want to start coding seriously. Web dev seems easier to get into (just need a browser). App dev needs Android Studio etc. But apps feel more "real". What did you guys start with?', 'Technology', true, 'Yuvraj Singh', 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=800', NULL, 234, 1340, now() - interval '17 hours'),

-- Memes / humor
('Why does school WiFi block everything 😩', 'Can''t open YouTube, can''t open Reddit, can''t open Discord. But somehow textsheet and discovery education work fine. Like who designed this filter?? At least give us Google Drive properly bro.', 'Technology', true, 'Aarav Khanna', 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=800', NULL, 567, 3890, now() - interval '8 hours'),
('Teacher: "the test is easy" — narrator: it was not', 'Maths test today. Teacher said it''ll be straightforward. First question: prove the cosine rule from scratch. SECOND question: integrate sin³x cos²x. I left half the paper blank 💀', 'Education', true, 'Ishaan Joshi', 'https://images.unsplash.com/photo-1606326608606-aa0b62935f2b?w=800', NULL, 789, 5230, now() - interval '14 hours'),

-- Hobbies
('Started a small Instagram theme page', '@cricket.factsindia — 3 weeks old, 240 followers. I post one cricket fact daily. Slowly growing. Anyone here run a theme page? How do you grow without paying for shoutouts?', 'Lifestyle', true, 'Pranav Singh', 'https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=800', NULL, 145, 870, now() - interval '11 hours'),
('Started doing photography with phone', 'Don''t have a DSLR. Just my OnePlus and golden hour walks around my colony. Posting on Instagram. The likes don''t matter but learning composition is fun. Should I save up for a proper camera or stick with phone?', 'Lifestyle', true, 'Arjun Bhardwaj', 'https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=800', NULL, 198, 1120, now() - interval '16 hours'),
('Tried sketching after years', 'Found my old sketchbook from class 6. Decided to draw something today. Made a portrait of my dog. It''s mid but the satisfaction of finishing it >>> any phone game. Why did I stop drawing??', 'Lifestyle', true, 'Aarush Mehta', 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=800', NULL, 267, 1560, now() - interval '20 hours'),

-- Cars / bikes
('Dad finally let me ride his Activa', 'I''m 16 and have my LL. Took it for a 5 min spin around the colony. Felt like Valentino Rossi for those 5 minutes. Throttle control is harder than it looks. Slowly building up to taking it to school.', 'Lifestyle', true, 'Daksh Goyal', 'https://images.unsplash.com/photo-1558981806-ec527fa84c39?w=800', NULL, 312, 1980, now() - interval '7 hours'),
('Dream car at 17: Toyota Supra MK4', 'I know I won''t afford it for like 20 years lol but the Supra is THE car. Watched Initial D and Fast and Furious too many times maybe. What''s your dream car?', 'Lifestyle', true, 'Tejas Iyer', 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800', NULL, 423, 2670, now() - interval '13 hours'),

-- Health / mental
('Skin breaking out before exams — coincidence?', 'Every single time exams come up, my face decides to revolt. Pimples everywhere. Is it stress or am I eating too much junk during prep? Started using a basic CeraVe routine. Lmk what works for you guys.', 'Lifestyle', true, 'Yug Bansal', 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800', NULL, 234, 1340, now() - interval '9 hours'),
('Trying to sleep before 12am — impossible task', 'Goal was 11pm bedtime. Reality: scrolling Instagram reels at 1:43am. Brain says sleep but thumb says one more reel. How do you guys actually sleep early??', 'Lifestyle', true, 'Vihaan Khanna', 'https://images.unsplash.com/photo-1531353826977-0941b4779a1c?w=800', NULL, 678, 4560, now() - interval '15 hours'),

-- College / career
('Confused between PCM and PCB', 'Class 10 results out. Got 92%. Mom wants me to take PCB (doctor in family). Dad says PCM (engineer life). I genuinely don''t know what I want yet. Anyone made this choice and regretted/loved it?', 'Education', true, 'Shivansh Rao', 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=800', NULL, 567, 3890, now() - interval '10 hours'),
('IIT vs NIT vs private — what really matters?', 'Bhaiya at coaching said IIT is the only thing that matters. But I see NIT/private college kids also doing well in life. Is the brand really worth that much extra grind?', 'Education', true, 'Ayaan Mehta', 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=800', NULL, 412, 2890, now() - interval '17 hours'),

-- Last few
('Reading books again — Atomic Habits review', 'My screen time was 9 hours daily. Decided to read instead. Picked up Atomic Habits. It''s actually really practical, not boring self-help fluff. The 1% better idea genuinely changed how I look at small habits.', 'Lifestyle', true, 'Aarav Iyer', 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=800', NULL, 345, 2230, now() - interval '11 hours'),
('Is ChatGPT cheating if I use it for homework?', 'Genuine debate. I use it to understand concepts, not copy paste answers. But some of my friends just paste the question and submit the output. Where''s the line? Teachers are starting to catch on.', 'Technology', true, 'Rishabh Mishra', 'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=800', NULL, 789, 5670, now() - interval '14 hours'),
('Made 3000 rupees from selling old comics', 'Had a stack of old Tinkle, Champak, Chacha Chaudhary lying around. Sold them on OLX for 3k. Bought myself headphones. Win win. Anyone else do small side hustles in school?', 'Lifestyle', true, 'Nakul Sharma', 'https://images.unsplash.com/photo-1592496431122-2349e0fbc666?w=800', NULL, 234, 1450, now() - interval '18 hours'),
('Boards over. Now what??', '12th boards officially done. Last paper was today. I literally don''t know what to do with my time. Slept for 14 hours yesterday. Plan: gym, gaming, learning to drive, and finally reading non-academic books. What do you guys do post-boards?', 'General', true, 'Kabir Joshi', 'https://images.unsplash.com/photo-1513258496099-48168024aec0?w=800', NULL, 456, 3120, now() - interval '21 hours');
